#' This script assembles source files containing objects, methods, and
#' {roxygen2} documentation for {dials} parameters for vectorizations of
#' persistent homology provided by {TDAvec}.
#'
#' To generate or update these files, execute the following:
#' source(here::here("build-pre/build-tdavec-params.R"))
#' 
#' Refer to the following resources for guidance:
#' https://blog.r-hub.io/2020/02/10/code-generation/
#' https://www.tidymodels.org/learn/develop/recipes/

#' SETUP

#' Set build parameters.

# standard prefix for built files
build_prefix <- "zzz"

# warning not to edit by hand
build_warning <- glue::glue(
  "# --------------------------------------",
  "----------------------------------------\n",
  "# Generated by 'build-pre/build-tdavec-params.R': do not edit by hand.\n",
  "# --------------------------------------",
  "----------------------------------------\n\n\n",
)

# source building utilities
source(here::here("build-pre/build-tdavec.R"))

Sys.sleep(.5)

#' GENERATORS

#' Generate parameter documentation.



#' Generate parameter functions.


#' WRITING

#' Write parameter source code.


