#' This script assembles source files containing objects, methods, and
#' {roxygen2} documentation for new dials that parameterize vectorizations of
#' persistent homology provided by {TDAvec}.
#'
#' To generate or update these files, execute the following:
#' source(here::here("pre-generate/generate-dials.R"))
#' 
#' Refer to the following resources for guidance:
#' https://blog.r-hub.io/2020/02/10/code-generation/
#' https://www.tidymodels.org/learn/develop/recipes/

#' SETUP

#' Set build parameters.

# standard prefix for built files
build_prefix <- "zzz"

# warning not to edit by hand
build_warning <- glue::glue(
  "# --------------------------------------",
  "----------------------------------------\n",
  "# Generated by 'pre-generate/generate-dials.R': do not edit by hand.\n",
  "# --------------------------------------",
  "----------------------------------------\n\n\n",
)

# source building utilities
source(here::here("pre-generate/utils-generate.R"))

#' WRITING

#' Initialize the source and example files.

# source file path
glue::glue("R/{build_prefix}-vpd-param.R") |> 
  here::here() ->
  r_file
# example file path
glue::glue("inst/examples/{build_prefix}-ex-vpd-param.R") |> 
  here::here() ->
  ex_file
# transforms to import from {scales}
dial_transforms |> 
  sapply(as.character) |> unique() |> 
  paste() -> imported_transforms

# header / front matter in {roxygen2}
frontmatter <- glue::glue(
  doc_wrap("@title Tune Vectorizations of Persistent Homology"),
  doc_wrap(""),
  doc_wrap("@description These tuning functions govern the parameters of"),
  # TODO: Add link when {TDAvec} has a package documentation page.
  doc_wrap("  vectorizations implemented in **TDAvec**."),
  doc_wrap("")
)

details <- list(doc_wrap("@details"), doc_wrap(""))
for (dl in param_autotuners) {
  
  # recover fields
  dl_name <- dl
  dl_arg <- param_args[[param_dials[[dl]]]]
  dl_funs <- tdavec_args |>
    filter(arg %in% param_args[dial_params[[dl]]]) |> 
    pull(funs) |> unlist() |> unname() |> 
    (\(s) paste0("[TDAvec::", s, "()]"))()
  dl_funs <- paste0(dl_funs, c(rep(",", length(dl_funs) - 1L), "."))
  
  # first line
  line1 <- paste0(
    "The parameter `", dl_name, "` is passed to `", dl_arg, "` in"
  )
  
  # format paragraph
  paragraph <- list(
    doc_wrap(line1),
    doc_wrap(dl_funs),
    doc_wrap("")
  )
  
  # append paragraph
  details <- c(details, paragraph)
}
# prepare for concatenation
details <- do.call(glue::glue, details)

# logistics in {roxygen2}
logistics <- glue::glue(
  doc_wrap("@name vpd-dials"),
  doc_wrap("@inheritParams dials::Laplace"),
  doc_wrap("@param values A character string of possible values."),
  doc_wrap("@inheritParams dials::finalize"),
  doc_wrap("@importFrom scales {imported_transforms}"),
  doc_wrap("@inheritParams step_pd_degree"),
  doc_wrap("@example inst/examples/{basename(ex_file)}"),
  "NULL\n",
  "\n"
)

# data for examples
example_data <- glue::glue(
  "data.frame(dist = I(list(eurodist, UScitiesD * 1.6))) %>%\n",
  "  transform(pd = I(lapply(dist, ripserr::vietoris_rips))) %>%\n",
  "  subset(select = c(pd)) %>%\n",
  "  print() -> pd_data\n",
  .trim = FALSE
)

# restart source file from scratch
cat(
  build_warning,
  frontmatter, details, logistics,
  file = r_file, sep = "\n", append = FALSE
)
# restart example file from scratch
cat(
  # build_warning,
  example_data,
  file = ex_file, sep = "\n", append = FALSE
)

#' Populate the source and example files with code.

# FIXME: Stop `NULL` from being treated as a finalizer.
for (dl in param_autotuners) {
  
  # recover fields
  dl_name <- dl
  dl_range_value <- dial_ranges_values[[dl]] |> 
    lapply(\(x) vapply(x, deparse, "")) |> 
    lapply(\(x) ifelse(grepl("^NA\\_", x), "unknown()", x)) |> 
    (\(s) paste0("c(", paste0(s, collapse = ", "), ")"))()
  dl_trans <- dial_transforms[[dl]] |> deparse()
  dl_class <- type_class[[dial_types[[dl]]]]
  dl_type <- dial_types[[dl]] |> deparse()
  dl_scope = if (dl_class == "qual") "values" else "range"
  dl_incl <- dial_inclusive[[dl]] |> deparse()
  dl_bullet <- dial_titles[[dl]] |> 
    gsub(pattern = "Number of ", replacement = "# ") |> 
    gsub(pattern = "\\?$", replacement = "")
  dl_fin <- dial_finalizers[[dl]] %||% "NULL"
  dl_steps <- tdavec_args |>
    filter(arg %in% param_args[dial_params[[dl]]]) |> 
    pull(funs) |> unlist() |> unname() |> 
    vec_sname() |> (\(s) paste0("`step_vpn_", s, "()`"))() |> 
    paste0(collapse = ", ")
  dl_abbr <- dl_name |> 
    snakecase::to_upper_camel_case() |> 
    gsub(pattern = "[a-z\\_]", replacement = "") |> 
    tolower()
  dl_range_value_ex <- dial_range_value_examples[[dl]] |> 
    lapply(\(x) vapply(x, deparse, "")) |> 
    lapply(\(x) ifelse(grepl("^NA\\_", x), "unknown()", x)) |> 
    (\(s) paste0("c(", paste0(s, collapse = ", "), ")"))()
  
  # append source code
  param_fill <- readLines("man/template/template-param.R") |> 
    gsub(pattern = "\\{dial_name\\}", replacement = dl_name) |> 
    gsub(pattern = "\\{dial_range_value\\}", replacement = dl_range_value) |> 
    gsub(pattern = "\\{dial_trans\\}", replacement = dl_trans) |> 
    gsub(pattern = "\\{dial_class\\}", replacement = dl_class) |> 
    gsub(pattern = "\\{dial_type\\}", replacement = dl_type) |> 
    gsub(pattern = "\\{dial_inclusive\\}", replacement = dl_incl) |> 
    gsub(pattern = "\\{dial_bullet\\}", replacement = dl_bullet) |> 
    gsub(pattern = "\\{dial_finalizer\\}", replacement = dl_fin) |> 
    gsub(pattern = "\\{dial_scope\\}", replacement = dl_scope)
  # if qual, remove quant-only lines
  if (dl_class == "qual") {
    rm_lines <- 
      ( grepl("(inclusive|trans) = ", param_fill) ) &
      ( seq_along(param_fill) > grep("new_qual_param", param_fill) )
    param_fill <- param_fill[! rm_lines]
  }
  write(param_fill, file = r_file, append = TRUE)
  
  # example 1 (all)
  example_1 <- glue::glue(
    paste0(
      "# `{dl_name}` for {dl_steps}\n",
      "\n",
      "({dl_abbr}_man <- {dl_name}({dl_scope} = {dl_range_value_ex}",
      if (dl_trans == "NULL") "" else ", trans = NULL", "))\n"
    ),
    "grid_regular({dl_abbr}_man)\n",
    "\n"
  )
  # example 2 (finalizers only)
  example_2 <- glue::glue(
    paste0("({dl_abbr}_dat <- {dl_name}() %>% {dl_fin}(x = pd_data))\n"),
    "grid_regular({dl_abbr}_dat)\n",
    "\n",
    paste0("({dl_abbr}_hom <- {dl_name}() %>% {dl_fin}(x = pd_data, hom_degrees = seq(2L)))\n"),
    "grid_regular({dl_abbr}_hom)\n",
    "\n"
  )
  
  # append examples
  c(example_1, if (dl_trans == "NULL") NULL else example_2) |> 
    write(file = ex_file, append = TRUE)
  
}
